import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Next } from "../components/Next";
import { Pic } from "../components/Pic";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col gap-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-grow min-h-screen py-20 flex flex-col gap-8 items-center justify-center">
        <h1 className="text-4xl font-semibold mb-8">
          Understanding observables
          <a
            className="text-blue-600 ml-4"
            href="https://rxjs.dev/guide/observable"
          >
            (RxJS!)
          </a>
        </h1>

        <h2 className="text-xl font-bold">
          What are observables (and by extension, what is RxJS)?
        </h2>

        <p className="max-w-lg text-gray-700 font-semibold italic">
          it's a tool that helps us control data as it goes through the flow of
          time - fireship.io
        </p>

        <p className="max-w-lg text-gray-700">
          observables are an abstraction that lets us with with streams. by
          streams i mean any data that unfolds over the dimension of time. some
          examples include updates from firebase's listeners, DOM events,
          websockets.
        </p>

        <Pic
          src="/images/default.png"
          caption="you're the person on the sofa"
        />

        <p className="max-w-lg text-blue-600">
          Let's frame this within a story. you're sitting at a sofa, and want to
          know about the weather. You decide it might be a great way to go to
          the beach if the weather is sunny.
        </p>

        <Next
          href="/sync"
          title="Synchronous"
          description="let's start by understanding how you get data synchronously"
        />
      </main>
    </div>
  );
};

export default Home;
